library(ggplot2)
library(stringr)
library(car)
library(arm)
library(plyr)
library(reshape)
library(ggmap)
library(DirichletReg)
library(rCharts)
library(testthat)
library(scales)
library(gridExtra)
library(RColorBrewer)
options(stringsAsFactors = TRUE)
